version: '3'
services:
  node-red:
    image: notfoundsam/node-red-swarm
    environment:
      - FLOWS=smart_remote.json
    ports:
      - "1880:1880"
      - "9090:9090"
    deploy:
      replicas: 1
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=smart_remote
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb
    deploy:
      replicas: 2
  grafana:
    image: fg2it/grafana-armhf:v5.1.3
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    deploy:
      replicas: 1

volumes:
  influx-data:
