version: '2'
services:
  node:
    image: python:2
    hostname: rpi-node-2
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "python -u node.py"
    networks:
      - smart-remote_rpi-net

networks:
  smart-remote_rpi-net:
    external: true
