version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=smart_remote
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - "3390:3306"
    networks:
      - rpi-net
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python run.py"
    working_dir: /app
    environment:
      - APP_ENV=development
      - APP_DOCKER=true
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
      - "5002:5002"
      - "9090:9090"
    privileged: true
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    networks:
      - rpi-net
  node-red:
    build:
      context: ./node-red
      dockerfile: Dockerfile
    environment:
      - FLOWS=smart_remote.json
    volumes:
      - ./node-red:/data:Z
    ports:
      - "1880:1880"
    user: node-red
    networks:
      - rpi-net
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=smart_remote
    volumes:
      - ./docker/influx-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - rpi-net
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - rpi-net
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - rpi-net

networks:
  rpi-net:
    driver: bridge

# volumes:
#   mysql-data:
#   influx-data:
