version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python run.py"
    working_dir: /app
    # environment:
    #   - APP_ENV=development
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    privileged: true
  node-red:
    image: easypi/node-red-arm
    ports:
      - "1880:1880"
    privileged: yes
    restart: always
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=smart_remote
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    image: fg2it/grafana-armhf:v5.1.3
    ports:
      - "3000:3000"
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
