version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python3","-u","run.py"]
    working_dir: /app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - APP_DOCKER=true
      - FLASK_APP=app/__init__.py
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
      - "5002:5002"
    privileged: true
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    networks:
      - smart-remote_rpi-net

networks:
  smart-remote_rpi-net:
    external: true
