version: '2'
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_rpi
  #   command: bash -c "python run.py"
  #   working_dir: /app
  #   # environment:
  #   #   - APP_ENV=development
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "5000:5000"
  #   privileged: true
  node-red:
    build:
      context: ./node-red
      dockerfile: Dockerfile_rpi
    environment:
      - FLOWS=smart_remote.json
    volumes:
      - ./node-red:/data:Z
    ports:
      - "1880:1880"
      - "9090:9090"
    privileged: yes
    restart: always
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=smart_remote
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    restart: always
  grafana:
    image: fg2it/grafana-armhf:v5.1.3
    ports:
      - "3000:3000"
    restart: always
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
