version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python run.py"
    working_dir: /app
    environment:
      - APP_ENV=development
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    expose:
      - "80"
