version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python run.py"
    working_dir: /app
    environment:
      - APP_ENV=development
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
  node-red:
    image: nodered/node-red-docker
    ports:
      - "1880:1880"
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=smart_remote
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
